language: python

dist: trusty

python:
  - 2.7
  - 3.6

cache: pip

env:
  - NUMPY_VERSION=1.7.1
  - NUMPY_VERSION=1.12.1
  
install:
  - docker build -t test-container --build-arg numpy_version=$NUMPY_VERSION .

script:
- docker run -v $PWD:/var/travis_tutorial test-container /bin/bash -c "cd /var/travis_tutorial && pytest"